### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/postfix#1]
package: 2:postfix-perl-scripts-3.2.0-1.module_c593e2d6.x86_64 from repoclosure-Server.x86_64
  unresolved deps: 
     perl(Date::Calc)

**Comment by phracek** [comment]
I guess, postfix-perl-scripts are not needed. The scripts analysis log. http://pkgs.fedoraproject.org/cgit/modules/postfix.git/commit/?h=f26&id=61f66129bb06cc2c2f822f662ac8e4cc5fde7afc

**Comment by r4f4** [comment]
Thank you for the fix. I'm closing this issue.
